### ISSUE TITLE
Docker下ffmpeg无法使用QSV硬件加速转码

### ISSUE THREAD

**Issue by Seameee** [renmu123/biliLive-tools#59]
### 我已尝试以下操作

- [x] 尝试使用 [最新版本](https://github.com/renmu123/biliLive-tools/releases)
- [x] 已阅读文档，并查询过 issue

### 复现步骤

以下为操作步骤，前半部分是docker容器中的bililive-tools日志，后半部分是在我宿主机上使用ffmpeg进行转码
```
Server is running at http://0.0.0.0:18010
SSE run ping: for 1 clients
SSE run ping: for 1 clients
{}
10:04:36.019 › danmakufactory command:  "/app/bin/DanmakuFactory" -i "/tmp/zx6w5e3lmvf.xml" -o "/tmp/biliLive-tools/0pealyyqj0y.ass" --ignore-warnings --resolution 1280x720 --scrolltime 9 --fixtime 4 --density -1 --fontname "SimHei" --fontsize 36 --opacity 255 --outline 1 --shadow 1 --displayarea 1 --scrollarea 0.5 --bold false --showusernames false --saveblocked true --showmsgbox false --msgboxsize 500x1080 --msgboxpos 20x0 --msgboxfontsize 38 --msgboxduration 10 --giftminprice 10 --blockmode null --timeshift 0
10:04:36.074 › ffmpeg task rofg7yud51 has been added, command: -i /app/video/14047 Zelo-Balance/2025年03月25日/Zelo-Balance-17时20分-从国际空间站俯瞰地球，静谧蓝星守护者.mp4 -y -filter_complex [0:v]subtitles=/tmp/biliLive-tools/0pealyyqj0y.ass[0:video] -map [0:video] -map 0:a -c:v h264_qsv -global_quality 18 -preset medium -c:a copy /app/video/14047 Zelo-Balance/2025年03月25日/test.mp4
10:04:36.145 › task rofg7yud51 start, command: ffmpeg -i /app/video/14047 Zelo-Balance/2025年03月25日/Zelo-Balance-17时20分-从国际空间站俯瞰地球，静谧蓝星守护者.mp4 -y -filter_complex [0:v]subtitles=/tmp/biliLive-tools/0pealyyqj0y.ass[0:video] -map [0:video] -map 0:a -c:v h264_qsv -global_quality 18 -preset medium -c:a copy /app/video/14047 Zelo-Balance/2025年03月25日/test.mp4
10:04:36.244 › task rofg7yud51 error: Error: ffmpeg exited with code 171: frame=    0 fps=0.0 q=0.0 Lsize=       0KiB time=N/A bitrate=N/A speed=N/A    
Conversion failed!
10:04:37.155 › sendByTg res {}
10:04:38.098 › sendByTg res {}
stream end 597721
SSE run ping: for 1 clients
SSE run ping: for 1 clients
Client closed connection
SSE run ping: for 1 clients
SSE run ping: for 1 clients
{}
10:06:06.273 › danmakufactory command:  "/app/bin/DanmakuFactory" -i "/tmp/kvi8sv5tlnc.xml" -o "/tmp/biliLive-tools/tqkdlrxwtrt.ass" --ignore-warnings --resolution 1280x720 --scrolltime 9 --fixtime 4 --density -1 --fontname "SimHei" --fontsize 36 --opacity 255 --outline 1 --shadow 1 --displayarea 1 --scrollarea 0.5 --bold false --showusernames false --saveblocked true --showmsgbox false --msgboxsize 500x1080 --msgboxpos 20x0 --msgboxfontsize 38 --msgboxduration 10 --giftminprice 10 --blockmode null --timeshift 0
10:06:06.284 › ffmpeg task 27dazedvpf7 has been added, command: -i /app/video/14047 Zelo-Balance/2025年03月25日/Zelo-Balance-17时20分-从国际空间站俯瞰地球，静谧蓝星守护者.mp4 -y -filter_complex [0:v]subtitles=/tmp/biliLive-tools/tqkdlrxwtrt.ass[0:video] -map [0:video] -map 0:a -c:v h264_qsv -global_quality 18 -preset medium -c:a copy /app/video/14047 Zelo-Balance/2025年03月25日/123.mp4
10:06:06.292 › task 27dazedvpf7 start, command: ffmpeg -i /app/video/14047 Zelo-Balance/2025年03月25日/Zelo-Balance-17时20分-从国际空间站俯瞰地球，静谧蓝星守护者.mp4 -y -filter_complex [0:v]subtitles=/tmp/biliLive-tools/tqkdlrxwtrt.ass[0:video] -map [0:video] -map 0:a -c:v h264_qsv -global_quality 18 -preset medium -c:a copy /app/video/14047 Zelo-Balance/2025年03月25日/123.mp4
10:06:06.379 › task 27dazedvpf7 error: Error: ffmpeg exited with code 171: frame=    0 fps=0.0 q=0.0 Lsize=       0KiB time=N/A bitrate=N/A speed=N/A    
Conversion failed!
10:06:07.338 › sendByTg res {}
10:06:07.360 › sendByTg res {}
SSE run ping: for 1 clients
^C%         

-----------以下内容为宿主机运行------------
                                                                                                                  
# seamee @ ubuntu in ~ [10:06:49] C:130
$ cd /mnt/nas/Bililive/14047\ Zelo-Balance/2025年03月25日 
# seamee @ ubuntu in /mnt/nas/Bililive/14047 Zelo-Balance/2025年03月25日 [10:07:19] 
$ ls             
Zelo-Balance-16时45分-从国际空间站俯瞰地球，静谧蓝星守护者.jpg
Zelo-Balance-16时45分-从国际空间站俯瞰地球，静谧蓝星守护者.json
Zelo-Balance-16时45分-从国际空间站俯瞰地球，静谧蓝星守护者.nfo
Zelo-Balance-16时45分-从国际空间站俯瞰地球，静谧蓝星守护者.ts
Zelo-Balance-17时20分-从国际空间站俯瞰地球，静谧蓝星守护者-弹幕版.mp4
Zelo-Balance-17时20分-从国际空间站俯瞰地球，静谧蓝星守护者.jpg
Zelo-Balance-17时20分-从国际空间站俯瞰地球，静谧蓝星守护者.mp4
Zelo-Balance-17时20分-从国际空间站俯瞰地球，静谧蓝星守护者.nfo
Zelo-Balance-17时20分-从国际空间站俯瞰地球，静谧蓝星守护者.xml
test.mp4
# seamee @ ubuntu in /mnt/nas/Bililive/14047 Zelo-Balance/2025年03月25日 [10:08:33] C:1
$  ffmpeg -i ./Zelo-Balance-17时20分-从国际空间站俯瞰地球，静谧蓝星守护者.mp4 -y -c:v h264_qsv -global_quality 18 -preset medium -c:a copy ./123.mp4
ffmpeg version 6.1.1-3ubuntu5 Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 13 (Ubuntu 13.2.0-23ubuntu3)
  configuration: --prefix=/usr --extra-version=3ubuntu5 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --disable-omx --enable-gnutls --enable-libaom --enable-libass --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libglslang --enable-libgme --enable-libgsm --enable-libharfbuzz --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-openal --enable-opencl --enable-opengl --disable-sndio --enable-libvpl --disable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-ladspa --enable-libbluray --enable-libjack --enable-libpulse --enable-librabbitmq --enable-librist --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libx264 --enable-libzmq --enable-libzvbi --enable-lv2 --enable-sdl2 --enable-libplacebo --enable-librav1e --enable-pocketsphinx --enable-librsvg --enable-libjxl --enable-shared
  libavutil      58. 29.100 / 58. 29.100
  libavcodec     60. 31.102 / 60. 31.102
  libavformat    60. 16.100 / 60. 16.100
  libavdevice    60.  3.100 / 60.  3.100
  libavfilter     9. 12.100 /  9. 12.100
  libswscale      7.  5.100 /  7.  5.100
  libswresample   4. 12.100 /  4. 12.100
  libpostproc    57.  3.100 / 57.  3.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from './Zelo-Balance-17时20分-从国际空间站俯瞰地球，静谧蓝星守护者.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf61.9.107
  Duration: 00:08:29.23, start: 0.000000, bitrate: 1182 kb/s
  Stream #0:0[0x1](und): Video: h264 (Main) (avc1 / 0x31637661), yuvj420p(pc, bt709, progressive), 1280x720, 858 kb/s, 30 fps, 30 tbr, 90k tbn (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
  Stream #0:1[0x2](und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 314 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> h264 (h264_qsv))
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
[swscaler @ 0x593305e46b40] deprecated pixel format used, make sure you did set range correctly
[swscaler @ 0x593305e54440] deprecated pixel format used, make sure you did set range correctly
libva info: VA-API version 1.22.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_22
libva info: va_openDriver() returns 0
libva info: VA-API version 1.22.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_22
libva info: va_openDriver() returns 0
    Last message repeated 2 times
Output #0, mp4, to './123.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf60.16.100
  Stream #0:0(und): Video: h264 (avc1 / 0x31637661), nv12(tv, bt709, progressive), 1280x720, q=2-31, 1000 kb/s, 30 fps, 15360 tbn (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
      encoder         : Lavc60.31.102 h264_qsv
    Side data:
      cpb: bitrate max/min/avg: 0/0/1000000 buffer size: 0 vbv_delay: N/A
  Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 314 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
[out#0/mp4 @ 0x593305d1f2c0] video:47870kB audio:19541kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.767848%
frame=15277 fps=318 q=19.0 Lsize=   67928kB time=00:08:29.16 bitrate=1092.9kbits/s speed=10.6x    
# seamee @ ubuntu in /mnt/nas/Bililive/14047 Zelo-Balance/2025年03月25日 [10:09:39] 
$ ls
123.mp4
Zelo-Balance-16时45分-从国际空间站俯瞰地球，静谧蓝星守护者.jpg
Zelo-Balance-16时45分-从国际空间站俯瞰地球，静谧蓝星守护者.json
Zelo-Balance-16时45分-从国际空间站俯瞰地球，静谧蓝星守护者.nfo
Zelo-Balance-16时45分-从国际空间站俯瞰地球，静谧蓝星守护者.ts
Zelo-Balance-17时20分-从国际空间站俯瞰地球，静谧蓝星守护者-弹幕版.mp4
Zelo-Balance-17时20分-从国际空间站俯瞰地球，静谧蓝星守护者.jpg
Zelo-Balance-17时20分-从国际空间站俯瞰地球，静谧蓝星守护者.mp4
Zelo-Balance-17时20分-从国际空间站俯瞰地球，静谧蓝星守护者.nfo
Zelo-Balance-17时20分-从国际空间站俯瞰地球，静谧蓝星守护者.xml
test.mp4
```

### 预期行为

能正常使用QSV硬件加速转码

### 实际行为

无法使用QSV硬件加速转码，使用CPU转码正常

### 分享log

[main.log](https://github.com/user-attachments/files/19478226/main.log)

**Comment by Seameee** [comment]
docker compose 文件
```yaml
version: "3"
services:
  # UI镜像
  webui:
    image: renmu1234/bililive-tools-frontend
    ports:
      # 前者按需改动
      - "13000:3000"
    network_mode: bridge
    restart: unless-stopped
  # 接口镜像
  api:
    image: renmu1234/bililive-tools-backend
    ports:
      - "18010:18010"
    volumes:
      # 映射的配置目录，用于持久化配置文件
      - ./data:/app/data
      # 用于处理webhook数据，按需修改，与录播姬的参数一致
      - /mnt/nas/Bililive:/app/video
      - /mnt/nas/volume2:/app/video2
      # 字体目录
      - ./fonts:/usr/local/share/fonts
    environment:
      # 登录密钥，自行修改
      - BILILIVE_TOOLS_PASSKEY=yycc.avjd520
      # 账户加密密钥，自行修改
      - BILILIVE_TOOLS_BILIKEY=yycc.avjd520
      # 中国时区
      - TZ=Asia/Shanghai
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    network_mode: bridge
    restart: unless-stopped
```

**Comment by Seameee** [comment]
好的，我尝试一下

**Comment by Seameee** [comment]
> 你需要自行进入容器中去安装相关驱动，具体可以参考一下 jellyfin 的[文档](https://jellyfin.org/docs/general/administration/hardware-acceleration/intel/)，目前没有编译好的docker可供选择，我手上也没合适的平台去测试，得靠你自己折腾了

尝试了一下成功调用了qsv转码，可能有冗余配置，抽空再改，下面是我的compose文件

![Image](https://github.com/user-attachments/assets/c89034f1-067e-4f28-b4a5-a87369140594)

```yaml    
services:
  # UI镜像
  webui:
    image: renmu1234/bililive-tools-frontend
    ports:
      # 前者按需改动
      - "13000:3000"
    network_mode: bridge
    restart: unless-stopped
  # 接口镜像
  api:
    image: renmu1234/bililive-tools-backend
    ports:
      - "18010:18010"
      # 添加render和video组，保证docker有权限调用显卡
    group_add:
      - "993"
      - video
    volumes:
      # 映射的配置目录，用于持久化配置文件
      - ./data:/app/data
      # 用于处理webhook数据，按需修改，与录播姬的参数一致
      - /mnt/nas/Bililive:/app/video
      - /mnt/nas/volume2:/app/video2
      # 字体目录
      - ./fonts:/usr/local/share/fonts
      # 直接使用主机驱动
      - /usr/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu
    environment:
      # 登录密钥，自行修改
      - BILILIVE_TOOLS_PASSKEY=yycc.avjd520
      # 账户加密密钥，自行修改
      - BILILIVE_TOOLS_BILIKEY=yycc.avjd520
      # 中国时区
      - TZ=Asia/Shanghai
      - LIBVA_DRIVER_NAME=iHD
      - LIBVA_DRIVERS_PATH=/usr/lib/x86_64-linux-gnu/dri
      # 添加显卡设备
    devices:
      - /dev/dri:/dev/dri
    network_mode: bridge
    restart: unless-stopped
```

**Comment by renmu123** [comment]
好耶，我之后把这个issue加入到文档中

**Comment by renmu123** [comment]
具体可能需要安装的包 https://github.com/intel/media-driver/wiki

**Comment by Hellrabb** [comment]
实际上将/usr/lib/x86_64-linux-gnu直接映射到docker可能存在一定的风险：比如docker bash环境里update一下导致宿主机环境坏掉，我这里分享一下我自己的操作方式（环境是ubuntu24.04,kernel 6.16）
1、映射/usr/lib/x86_64-linux-gnu/dri:/usr/lib/x86_64-linux-gnu/dri
2、docker bash参考intel文档安装https://dgpu-docs.intel.com/driver/client/overview.html 参考22.04部分, docker bash环境看起来是debian 12的）
3、apt install libva-drm2 vainfo vim -y（个人习惯）
4、测试命令如下（写的不一定对。。）：/app/bin/ffmpeg -v verbose -init_hw_device qsv=va:/dev/dri/renderD128 -init_hw_device opencl@va,出现MFX session没有报错就行

**Comment by Seameee** [comment]
> 实际上将/usr/lib/x86_64-linux-gnu直接映射到docker可能存在一定的风险：比如docker bash环境里update一下导致宿主机环境坏掉，我这里分享一下我自己的操作方式（环境是ubuntu24.04,kernel 6.16） 1、映射/usr/lib/x86_64-linux-gnu/dri:/usr/lib/x86_64-linux-gnu/dri 2、docker bash参考intel文档安装https://dgpu-docs.intel.com/driver/client/overview.html 参考22.04部分, docker bash环境看起来是debian 12的） 3、apt install libva-drm2 vainfo vim -y（个人习惯） 4、测试命令如下（写的不一定对。。）：/app/bin/ffmpeg -v verbose -init_hw_device qsv=va:/dev/dri/renderD128 -init_hw_device opencl@va,出现MFX session没有报错就行

映射路径可以设置只读权限吧，不知道能不能起效，不过我很久没折腾了

**Comment by 4thHydrogen** [comment]
我这里是用AI折腾了一下，找到了一个解决方案。可以供大家参考一下。将这两个文件放在同一个目录下，并执行下面的命令，就可以运行了。
```
docker compose build --no-cache
docker compose up -d
```
## docker compose
路径映射就请自行按需修改。
- lib和ffmpeg这两个文件的路径具体在哪里就问问AI吧，让他帮你解决。
- LD_LIBRARY_PATH=/usr/trim/lib/mediasrv/lib 这个也要记得修改。
```
services:
  fullstack:
    build: .
    container_name: biliLive-tools
    restart: unless-stopped
    privileged: true
    user: "0:0"
    ports:
      - "3000:3000"
    volumes:
      - /vol1/1000/docker/bilibili_recorder/bililive-tools/data:/app/data
      - /vol3/1000/media/record:/app/video
      - /vol1/1000/docker/bilibili_recorder/fonts:/usr/local/share/fonts
      # 仅库和二进制文件，我的情况是一定需要使用宿主机的。不然的话就会报错。
      - /usr/trim/lib/mediasrv/lib:/usr/trim/lib/mediasrv/lib:ro
      - /usr/trim/lib/mediasrv/ffmpeg:/opt/trim/bin/ffmpeg:ro
    environment:
      - PUID=1000
      - PGID=1001
      - BILILIVE_TOOLS_PASSKEY=123123
      - BILILIVE_TOOLS_BILIKEY=123123
      - TZ=Asia/Shanghai
      # 【核心修改】同步改成真实路径
      - LD_LIBRARY_PATH=/usr/trim/lib/mediasrv/lib
      - LIBVA_DRIVER_NAME=iHD
      
    group_add:
      - "105"
      
    devices:
      - /dev/dri/card0:/dev/dri/card0
      - /dev/dri/renderD128:/dev/dri/renderD128
```

## dockerfile
这个是 Dockerfile 文件，一并放在 Docker 的目录下。
```
FROM renmu1234/bililive-tools:latest

USER root
#这是我自己的代理，你可以删掉或者改成你需要的。
ENV HTTP_PROXY=http://192.168.50.12:7897
ENV HTTPS_PROXY=http://192.168.50.12:7897

# 【核心修改】彻底删掉了 libva2 和 libva-drm2，绝不允许版本冲突
RUN apt-get update && apt-get install -y --no-install-recommends \
    ocl-icd-libopencl1 \
    libopenmpt0 \
    libbluray2 \
    libvpx7 \
    libzvbi0 \
    libtheora0 \
    libx264-164 \
    libigdgmm12 \
    libmfx1 \
    && rm -rf /var/lib/apt/lists/*

RUN mv /app/bin/ffmpeg /app/bin/ffmpeg.bak 2>/dev/null || true
RUN ln -s /opt/trim/bin/ffmpeg /app/bin/ffmpeg

USER node
```
